version: "3.7"

services:
  db:
    container_name: "app_db"
    image: "postgres:14.7-alpine"
    restart: always

    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"