# Generated by Django 4.1.7 on 2023-04-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "presentation",
            "0002_author_category_secondtablebooks_authorprofile_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="secondtablebooks",
            table=None,
        ),
    ]
